version: '3'
services:
    screeps:
        image: screepers/screeps-launcher
        volumes:
            - ./config.yml:/screeps/config.yml
            - ./bots:/screeps/bots
            - screeps-data:/screeps
        ports:
            - {{ serverPort }}:21025/tcp
            - {{ cliPort }}:21026
        environment:
            MONGO_HOST: mongo
            REDIS_HOST: redis
        restart: unless-stopped

    mongo:
        image: mongo
        volumes:
        - mongo-data:/data/db
        restart: unless-stopped
        logging:
            driver: "none"

    redis:
        image: redis
        logging:
            driver: "none"
        volumes:
        - redis-data:/data
        restart: unless-stopped
        logging:
            driver: "none"
            
volumes:
    screeps-data:
    redis-data:
    mongo-data: